name: comparador_de_precos
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  device_preview: ^1.2.0
  equatable: ^2.0.7
  firebase_core: ^3.13.0
  supabase_flutter: ^2.9.1
  get_it: ^8.0.3
  flutter_gutter: ^2.2.0
  shared_preferences: ^2.5.3
  hugeicons: ^0.0.11
  cached_network_image: ^3.4.1
  star_rating: ^0.11.0
  timeago: ^3.7.1
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  font_awesome_flutter: ^10.8.0
  uuid: ^4.5.1
  mockito: ^5.4.6
  skeletonizer: ^2.0.1
  file_picker: ^10.2.0
  flutter_barcode_scanner:
    git:
      url: https://github.com/giovanninibarbosa/flutter_barcode_scanner
  clarity_flutter: ^1.0.0
  nif_validator: ^2.0.0

  #pdf
  path_provider: ^2.1.5
  syncfusion_flutter_core: ^30.1.40
  syncfusion_flutter_datagrid: ^30.1.40
  syncfusion_flutter_datagrid_export: ^30.1.40
  share_plus: ^11.0.0
  form_field_validator: ^1.1.0
  mask_text_input_formatter: ^2.9.0
  faker: ^2.2.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/